package main

import "fmt"
import "time"
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
func main() {
    start := time.Now()
    res := fibo(4000000)
    fmt.Println(time.Since(start))
    fmt.Println(res)
}

func fibo(below int) int {
    sum := 2
    first := 1
    second := 2 
    for i := first+second; i < below; i = first+second  {
        if(i % 2 == 0){
            sum += i
        }
        first = second
        second = i
    }
    return sum
}
